In [79]:
import pandas as pd
import numpy as np

In [80]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('/Users/siddharthkushwaha/Desktop/ML/day-34-handling-date-time/day34-handling-date-and-time/messages.csv')

In [81]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [82]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [83]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

### Working with Dates

In [84]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [85]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [86]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
349 2018-09-02        5819       25       4       2018
460 2019-01-25        5508       14       9       2019
130 2019-07-12        2242        8       2       2019
801 2018-12-17         630       10      12       2018
11  2019-08-02        3311       22       6       2019

In [87]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

## Extract Days

In [88]:
date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year  date_month_no  date_day
0 2019-12-10        5628       25       3       2019             12        10
1 2018-08-15        3646       14     157       2018              8        15
2 2018-10-23        1859       25       1       2018             10        23
3 2019-08-17        7292       25       1       2019              8        17
4 2019-01-06        4344       25       3       2019              1         6

In [89]:

# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [90]:

# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019             12        10         1       Tuesday
1 2018-08-15       2018              8        15         2     Wednesday
2 2018-10-23       2018             10        23         1       Tuesday
3 2019-08-17       2019              8        17         5      Saturday
4 2019-01-06       2019              1         6         6        Sunday

In [91]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,10,1,Tuesday,0
1,2018-08-15,2018,8,15,2,Wednesday,0
2,2018-10-23,2018,10,23,1,Tuesday,0
3,2019-08-17,2019,8,17,5,Saturday,1
4,2019-01-06,2019,1,6,6,Sunday,1

### Extract week of the year

In [92]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,10,1,Tuesday,0,50
1,2018-08-15,2018,8,15,2,Wednesday,0,33
2,2018-10-23,2018,10,23,1,Tuesday,0,43
3,2019-08-17,2019,8,17,5,Saturday,1,33
4,2019-01-06,2019,1,6,6,Sunday,1,1

### Extract Quarter

In [93]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,6,6,Sunday,1,1,1

### Extract Semester

In [94]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,6,6,Sunday,1,1,1,1

### Extract Time elapsed between dates

In [95]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 8, 1, 0, 10, 20, 34864)

In [96]:
today - date['date']

0     2426 days 00:10:20.034864
1     2908 days 00:10:20.034864
2     2839 days 00:10:20.034864
3     2541 days 00:10:20.034864
4     2764 days 00:10:20.034864
                 ...
995   2854 days 00:10:20.034864
996   2795 days 00:10:20.034864
997   2643 days 00:10:20.034864
998   2708 days 00:10:20.034864
999   2482 days 00:10:20.034864
Name: date, Length: 1000, dtype: timedelta64[ns]

In [105]:
(today - date['date']).dt.days

0      2426
1      2908
2      2839
3      2541
4      2764
       ...
995    2854
996    2795
997    2643
998    2708
999    2482
Name: date, Length: 1000, dtype: int64

In [107]:
# Months passed

np.round((today - date['date']).dt.days / 30.44, 0)

0      80.0
1      96.0
2      93.0
3      83.0
4      91.0
       ...
995    94.0
996    92.0
997    87.0
998    89.0
999    82.0
Name: date, Length: 1000, dtype: float64

In [108]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [110]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [111]:

time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

### Extract Time part

In [112]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### Time difference

In [113]:
today - time['date']

0     4611 days 23:20:20.034864
1     4476 days 00:30:20.034864
2     4961 days 23:49:20.034864
3     4263 days 23:39:20.034864
4     4661 days 00:59:20.034864
                 ...
995   5250 days 23:20:20.034864
996   4572 days 00:56:20.034864
997   5037 days 00:33:20.034864
998   5153 days 00:36:20.034864
999   4425 days 00:45:20.034864
Name: date, Length: 1000, dtype: timedelta64[ns]

In [114]:

# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.984744e+08
1      3.867282e+08
2      4.287162e+08
3      3.684084e+08
4      4.027140e+08
           ...
995    4.536840e+08
996    3.950242e+08
997    4.351988e+08
998    4.452214e+08
999    3.823227e+08
Name: date, Length: 1000, dtype: float64

In [115]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.641240e+06
1      6.445470e+06
2      7.145269e+06
3      6.140139e+06
4      6.711899e+06
           ...
995    7.561400e+06
996    6.583736e+06
997    7.253313e+06
998    7.420356e+06
999    6.372045e+06
Name: date, Length: 1000, dtype: float64

In [116]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      110687.338899
1      107424.505565
2      119087.822232
3      102335.655565
4      111864.988899
           ...
995    126023.338899
996    109728.938899
997    120888.555565
998    123672.605565
999    106200.755565
Name: date, Length: 1000, dtype: float64